// ════════════════════════════════════════════════════════════
// 文章数据.js — 文学板块文章 (理学文章已拆至 理学文章.js)
// 板块: 文学 (随笔/设计/图形)   格式: txt / html / svg, 不支持 Markdown
// 说明: 经典脚本, file:// 下可加载; 挂 window.文章数据
// 拆分记录 2026-09-03: 理学 8 篇 + 命令表 → 理学文章.js (window.理学文章)
// ════════════════════════════════════════════════════════════
(function (根) {
  'use strict';

  const 文章表 = [
    {"标题":"白色 + 粉色主题设计说明 (HTML)","作者":"truenice2","日期":"2026-09-03","标签":["设计","主题","HTML"],"格式":"html","板块":"文学","正文":"\n<h3>配色变量</h3>\n<table>\n  <tr><th>变量</th><th>色值</th><th>用途</th></tr>\n  <tr><td>--主色</td><td><code>#d4456f</code></td><td>玫红主色 (顶栏渐变 / 按钮)</td></tr>\n  <tr><td>--次色</td><td><code>#f6a5c0</code></td><td>浅粉 (描边 / 悬停)</td></tr>\n  <tr><td>--背景</td><td><code>#fdf7fa</code></td><td>极浅粉底</td></tr>\n  <tr><td>--边框</td><td><code>#f0e2ea</code></td><td>卡片分隔线</td></tr>\n</table>\n<h3>布局层次</h3>\n<ul>\n  <li><b>顶栏</b> — fixed 定位, 向下滚动隐藏, 向上滚动显示</li>\n  <li><b>侧栏</b> — 可折叠, 收起后内容区网格列数自动变密</li>\n  <li><b>卡片</b> — 12px 圆角 + 淡粉阴影, 悬停上移 3px</li>\n  <li><b>弹窗</b> — 遮罩 + 缩放弹入动画, Esc 关闭</li>\n</ul>\n<blockquote>本站不使用 Markdown, 文档统一用 txt / html / svg 三种格式,\n这一篇就是 html 格式的示例。</blockquote>"},
    {"标题":"门户架构图 (SVG)","作者":"truenice2","日期":"2026-09-03","标签":["架构","SVG"],"格式":"svg","板块":"文学","正文":"<svg viewBox=\"0 0 620 300\" xmlns=\"http://www.w3.org/2000/svg\" style=\"width:100%;height:auto\">\n  <rect width=\"620\" height=\"300\" fill=\"#fdf7fa\" rx=\"10\"/>\n  <text x=\"310\" y=\"28\" text-anchor=\"middle\" font-size=\"17\" fill=\"#b8375c\" font-weight=\"bold\">GH 资源门户 · 架构分层</text>\n\n  <rect x=\"40\" y=\"50\" width=\"160\" height=\"52\" rx=\"8\" fill=\"#d4456f\"/>\n  <text x=\"120\" y=\"72\" text-anchor=\"middle\" font-size=\"13\" fill=\"#fff\">网站主页.htm</text>\n  <text x=\"120\" y=\"90\" text-anchor=\"middle\" font-size=\"11\" fill=\"#ffe3ee\">骨架 + ESM 加载器</text>\n\n  <rect x=\"230\" y=\"50\" width=\"160\" height=\"52\" rx=\"8\" fill=\"#f6a5c0\"/>\n  <text x=\"310\" y=\"72\" text-anchor=\"middle\" font-size=\"13\" fill=\"#7a2b47\">网站主页.js (核心)</text>\n  <text x=\"310\" y=\"90\" text-anchor=\"middle\" font-size=\"11\" fill=\"#7a2b47\">存储 / 路由 / 业务</text>\n\n  <rect x=\"420\" y=\"50\" width=\"160\" height=\"52\" rx=\"8\" fill=\"#f6a5c0\"/>\n  <text x=\"500\" y=\"72\" text-anchor=\"middle\" font-size=\"13\" fill=\"#7a2b47\">网页操作.js (渲染)</text>\n  <text x=\"500\" y=\"90\" text-anchor=\"middle\" font-size=\"11\" fill=\"#7a2b47\">DOM / 事件 / 弹窗</text>\n\n  <rect x=\"40\" y=\"130\" width=\"250\" height=\"52\" rx=\"8\" fill=\"#ffffff\" stroke=\"#f0e2ea\"/>\n  <text x=\"165\" y=\"152\" text-anchor=\"middle\" font-size=\"13\" fill=\"#2d2a2e\">网站数据.js</text>\n  <text x=\"165\" y=\"170\" text-anchor=\"middle\" font-size=\"11\" fill=\"#8a8490\">资源 / 加速源 / 命令 / 导航</text>\n\n  <rect x=\"330\" y=\"130\" width=\"250\" height=\"52\" rx=\"8\" fill=\"#ffffff\" stroke=\"#f0e2ea\"/>\n  <text x=\"455\" y=\"152\" text-anchor=\"middle\" font-size=\"13\" fill=\"#2d2a2e\">文章数据.js</text>\n  <text x=\"455\" y=\"170\" text-anchor=\"middle\" font-size=\"11\" fill=\"#8a8490\">txt / html / svg 文章</text>\n\n  <rect x=\"40\" y=\"210\" width=\"540\" height=\"52\" rx=\"8\" fill=\"#ffffff\" stroke=\"#f0e2ea\"/>\n  <text x=\"310\" y=\"232\" text-anchor=\"middle\" font-size=\"13\" fill=\"#2d2a2e\">三层存储: localStorage (主) · IndexedDB (idb) · sql.js (WASM)</text>\n  <text x=\"310\" y=\"250\" text-anchor=\"middle\" font-size=\"11\" fill=\"#8a8490\">CDN: marked 已移除 · idb / sql.js 多源回退 · 断网自动降级</text>\n\n  <path d=\"M200 76 L228 76\" stroke=\"#d4456f\" stroke-width=\"2\" marker-end=\"url(#a)\"/>\n  <path d=\"M390 76 L418 76\" stroke=\"#d4456f\" stroke-width=\"2\" marker-end=\"url(#a)\"/>\n  <path d=\"M120 104 L120 128\" stroke=\"#d4456f\" stroke-width=\"2\" marker-end=\"url(#a)\"/>\n  <path d=\"M310 104 L310 128\" stroke=\"#d4456f\" stroke-width=\"2\" marker-end=\"url(#a)\"/>\n  <defs>\n    <marker id=\"a\" markerWidth=\"8\" markerHeight=\"8\" refX=\"6\" refY=\"3\" orient=\"auto\">\n      <path d=\"M0,0 L6,3 L0,6 Z\" fill=\"#d4456f\"/>\n    </marker>\n  </defs>\n</svg>"},
    {"标题":"浅粉色的下午: 一次配色的取舍","作者":"truenice2","日期":"2026-09-03","标签":["随笔","配色"],"格式":"txt","板块":"文学","正文":"━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n  浅粉色的下午: 一次配色的取舍\n  作者: truenice2   更新: 2026-09-03\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n一开始我选的是玫红 #d4456f, 顶栏铺满, 整个站像一颗糖。\n看了半小时, 眼睛开始累 —— 饱和度高的颜色适合点缀,\n不适合当底色, 更不适合长时间阅读。\n\n于是把主色调浅:\n\n  主色   #d4456f  →  #f7a8c4    浅粉, 用在按钮与强调\n  次色   #f6a5c0  →  #fbd8e6    更浅, 用在描边与悬停\n  背景   #fdf7fa  →  #fffafd    近白, 只留一点点粉\n  文字   #2d2a2e  →  #4a4048    略调暖, 与粉底更协调\n\n顶栏改成浅粉渐变配深粉文字, 而不是白字压深红。\n白底 + 浅粉, 像纸上的淡淡荧光笔痕迹: 有记忆点,\n但不抢内容的位置。\n\n取舍的原则只有一条: 颜色要让位给内容。\n一本书的封面可以鲜艳, 内页必须安静。\n"},
    {"标题":"我把整个工作区装进了一个 htm","作者":"truenice2","日期":"2026-09-03","标签":["随笔","静态站"],"格式":"txt","板块":"文学","正文":"━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n  我把整个工作区装进了一个 htm\n  作者: truenice2   更新: 2026-09-03\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n这些年在 F 盘攒了几十个项目: 门户、博客、影评、\n棋类、编辑器、游戏、AI 助手、内网穿透……\n每次想找一个命令, 都要在资源管理器里翻半天。\n\n后来我做了一个决定: 把它们全部写进数据文件,\n用一个 htm 串起来。\n\n于是有了这个门户:\n\n  · 双击 网站主页.htm 就能打开, 不需要装任何东西\n  · 断网也能用: 数据在本地, 存储也在本地\n  · 换电脑时, 拷一个目录就走\n  · 需要分享时, 推到 GitHub Pages 或 Cloudflare Pages\n\n有意思的是, 做了这个门户之后, 我最常用的功能\n不是花哨的卡片, 而是那个命令速查表 ——\ngh auth login 到底要不要加 --web,\n每次都要查。\n\n工具的价值, 往往就藏在这种\"每天都会忘一次\"的地方。\n"}
  ];

  const 数据 = {
    文章表,
    格式表: ['txt', 'html', 'svg'],
    板块: '文学',
    版本: 'v1.4',
    生成时间: '2026-09-03',
  };

  根.文章数据 = 数据;

  if (typeof module !== 'undefined' && module.exports) module.exports = 数据;
})(typeof window !== 'undefined' ? window : globalThis);
